version: '3.1'

services:

  wordpress:
    build: ./wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: instancetwo
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: instance-two
    volumes:
      - wordpress:/var/www/html
    

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: instance-two
      MYSQL_USER: instancetwo
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: